spring.application.name=servelq
server.port=${PORT:8085}
spring.jackson.mapper.accept-case-insensitive-enums=true
logging.level.com.gis.servelq.services=DEBUG
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/serveiq
spring.datasource.username=serveiq
spring.datasource.password=Insync2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
twilio.sid=AC31f111ff92893d6319a3e96fa4bed3f6
twilio.token=0606ff938e33d9c13a6e5e5206a28ade
twilio.from=whatsapp:+14155238886
# Disable Hibernate SQL logs
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
# Disable Hibernate statistics
logging.level.org.hibernate.stat=OFF
# Your application logs
logging.level.com.gis.servelq=DEBUG
# Spring framework logs (optional)
logging.level.org.springframework=INFO
# Spring Security (if still needed)
logging.level.org.springframework.security=INFO
logging.level.org.apache.catalina=OFF
logging.level.org.apache.tomcat=OFF
#logging.level.org.springframework.web=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
